version: "3.8"

services:
  nats:
    image: nats:2.11
    container_name: nats
    restart: always
    ports:
      - "4222:4222"

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    restart: always
    depends_on:
      - nats
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "50051:50051"

  order-service:
    build: ./services/order-service
    container_name: order-service
    restart: always
    depends_on:
      - nats
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "50053:50053"

  product-service:
    build: ./services/product-service
    container_name: product-service
    restart: always
    depends_on:
      - nats
      - auth-service
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
      - AUTH_SERVICE_ADDR=auth-service:50051
    ports:
      - "50052:50052"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - auth-service
      - order-service
      - product-service
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_ADDR=auth-service:50051
      - ORDER_SERVICE_ADDR=order-service:50053
      - PRODUCT_SERVICE_ADDR=product-service:50052
    ports:
      - "8080:8080"

volumes:
  mongo_data:
