version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass ${REDIS_PASS}
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASS}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  nats:
    image: nats:latest
    ports:
      - "4222:4222"
    command: ["-js", "-m", "8222"]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8222/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    build: ./services/auth-service
    container_name: auth-service
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
      nats:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
      - REDIS_ADDR=redis:6379
      - REDIS_PASS=${REDIS_PASS}
    ports:
      - "50051:50051"
    healthcheck:
      test: ["CMD-SHELL", "grpc_health_probe -addr=:50051 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  order-service:
    build: ./services/order-service
    container_name: order-service
    restart: always
    depends_on:
      - nats
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
    ports:
      - "50053:50053"

  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    container_name: product-service
    restart: always
    depends_on:
      - nats
      - auth-service
    env_file:
      - .env
    environment:
      - NATS_URL=nats://nats:4222
      - AUTH_SERVICE_ADDR=auth-service:50051
    ports:
      - "50052:50052"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    restart: always
    depends_on:
      - auth-service
      - order-service
      - product-service
    env_file:
      - .env
    environment:
      - AUTH_SERVICE_ADDR=auth-service:50051
      - ORDER_SERVICE_ADDR=order-service:50053
      - PRODUCT_SERVICE_ADDR=product-service:50052
    ports:
      - "8080:8080"

volumes:
  redis_data:
