version: '3.8'

services:
  # Databases
  db:
    image: postgres:16
    container_name: auth_db
    env_file: 
      - path: ./.database.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      timeout: 5s
      retries: 100

  # Redis
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 100

  # NATS
  nats:
    image: nats:2.9
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    healthcheck:
      test: ["CMD", "nats", "ping"]
      interval: 5s
      timeout: 5s
      retries: 100

  # Monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus:/etc/prometheus
    ports:
      - "9090:9090"
    depends_on:
      - nats
      - redis
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:9090/-/healthy"]
      interval: 10s
      timeout: 5s
      retries: 10

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    volumes:
      - ./monitoring/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 10

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter
    container_name: postgres_exporter
    command:
      - "--config.file=/etc/postgres_exporter/postgres_exporter.yml"
    env_file: "./.database.env"
    volumes:
      - ./monitoring/postgres_exporter:/etc/postgres_exporter:ro
    ports:
      - "9187:9187"
    depends_on:
      db:
        condition: service_healthy

  redis_exporter:
    image: oliver006/redis_exporter
    ports:
    - "9121:9121"
    depends_on:
    - redis

volumes:
  auth_db_data:
  product_db_data:
  order_db_data:
  payment_db_data: